### PR TITLE
Add URLSession support to Client

### PR DESCRIPTION
**Pull request by ftp27**
I've got an error which is mentioned in issue #44. So I'm wondering if we can use URLSession to send requests.

### CODE REVIEW

**Review by dylanshine — CHANGES_REQUESTED** [review]

**Comment by ftp27** [comment]
@dylanshine Thank you for the review. I'm really not sure I fixed part fix Linux. I don't have Linux to check it, hope it'll work.

**Comment by dylanshine** [comment]
@ftp27 The easiest thing here would probably he to wrap the Linux code with "#if os(Linux)" and define the macOS code in the else

**Comment by ftp27** [comment]
@dylanshine Yep. I've done it in https://github.com/dylanshine/openai-kit/pull/47/commits/cfe369095a314a87d6d365d713c9f31a55232aa2

**Comment by ftp27** [comment]
@dylanshine Is there anything else I can do?

**Comment by dylanshine** [comment]
@ftp27 Sorry, was out of town. You're on the right track, you just need to wrap the inverse as macOS compatible code will not run on Linux, however Linux code will run on macOS.

**Comment by ftp27** [comment]
@dylanshine I tried to build a small executable app in docker. So now I see. It seems like Linux doesn't have async methods for URLSession (https://github.com/apple/swift-corelibs-foundation/issues/3205). Shell we just cut the feature off for Linux or reimplement async methods?

**Comment by dylanshine** [comment]
@ftp27 I think you can get this to work by just checking for macOS explicitly. On mac, you allow users to consume both the HTTPClient and URLSession APIs, and on Linux just the HTTPClient

**Comment by ftp27** [comment]
@dylanshine I removed the URLSession code for Linux. Not in builds on it at least

**Review by dylanshine — APPROVED** [review]

**Pull request merged**
