### PR TITLE
Fix capatable for turbo0301 model

### PR DESCRIPTION
**Pull request by KittenYang**

### CODE REVIEW

**Comment by ronaldmannak** [comment]
Just trying to understand the code. You made the properties optional because the API doesn't always return the properties? Is that why you kept the init non-optional?

**Comment by KittenYang** [comment]
@ronaldmannak yep

**Comment by dylanshine** [comment]
@KittenYang Can you provide example requests/responses?

**Comment by dylanshine** [comment]
Closed due to inactivity.

**Pull request closed without merging**
